training_args:
  output_dir: "experiments/hh_self_judge"
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 1
  gradient_checkpointing: True
  learning_rate: 5e-6
  lr_scheduler_type: "constant_with_warmup"
  warmup_ratio: 0.1
  num_train_epochs: 3
  logging_steps: 1
  report_to: "wandb"
  save_strategy: "epoch"
  seed: 42
  remove_unused_columns: False
  bf16: True

self_judge_args:
  token_id_a: 319
  token_id_b: 350
  disable_dropout: True
  judge_batch_size: 8
  max_length: 2048
  max_new_tokens: 768
  top_p: 0.9
  temperature: 1.0
  loss_type: "sigmoid"
  beta: 0.1

model:
  pretrained_model_name_or_path: "experiments/hh_jsft"
  attn_implementation: "flash_attention_2"

peft_config:
  r: 8
  lora_alpha: 16
  lora_dropout: 0.1

templates:
  skip_first_token: True
  chat: "<|system|>\n{% for message in messages %}{% if loop.first and message['role'] == 'system' %}{{ message['content'] }}{% elif message['role'] == 'user' %}{{ '\n<|user|>\n' + message['content']}}{% elif message['role'] == 'assistant' %}{{ '\n<|assistant|>\n' + message['content'] + eos_token }}{% endif %}{% if loop.last and add_generation_prompt %}\n{{ '\n<|assistant|>\n' }}{% endif %}{% endfor %}"
  user: "\n<|user|>\n"
  assistant: "\n<|assistant|>\n"
  judge:
    helpful: 
      system: "Below are a series of dialogues between a human user and an AI assistant. The AI tries to be helpful, harmless, and honest."
      user: "Which is the more helpful, harmless, and honest assistant from a given context?\n\nContext:\n-----\n{context}\n-----\n\nAssistant A: {response_a}\nAssistant B: {response_b}\n\nPlease choose either A or B."
      assistant: "Sure! The option which is more helpful, harmless, and honest would be Assistant"
  
dataset: "Anthropic/hh-rlhf"
